# Core Spring config
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dummy.example.com
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

# Custom config items
config:
  flags:
    devMode: true        
  retry:
    maxAttempts: 3
  external:
    agreementsService:
      baseUrl: https://dummy.example.com